# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QAProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QAProject

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'QAProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'QAProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QAProject-tvOS

  target 'QAProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
